name: magic_deck_manager
description: A deck manager for magic the gathering.
publish_to: 'none'

version: 0.2.5+7

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  json_annotation: ^4.8.1
  sqflite: ^2.3.0
  path: ^1.8.3
  freezed_annotation: ^2.4.1
  sqflite_common_ffi: ^2.3.0+2
  uuid: ^4.1.0
  flutter_svg: ^2.0.7
  shared_preferences: ^2.2.2
  collection:
  package_info_plus: ^4.2.0
  url_launcher: ^6.1.14
  dynamic_color: ^1.6.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.5

  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

  assets:
    - data/AtomicCards.json
    - data/SetList.json
    - data/AllPrintings.sqlite
    - assets/mana-icons/
    - assets/icon/logo.svg
  
  fonts:
    - family:  CustomIcons
      fonts:
       - asset: fonts/CustomIcons.ttf

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#274625"
  adaptive_icon_foreground: "assets/icon/logo_fg.png"
  web:
    generate: true
    image_path: "assets/icon/logo.png"
    background_color: "#274625"
    theme_color: "#274625"
  windows:
    generate: true
    image_path: "assets/icon/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/logo.png"
