/// Flutter icons CustomIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
// ignore_for_file: constant_identifier_names
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
/// * Zocial, Copyright (C) 2012 by Sam Collins
///         Author:    Sam Collins
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  http://zocial.smcllns.com/
///

import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData cards_outlined = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cards_filled = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData deck_outlined = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData deck_filled = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github_circled = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
